Create kit fertility_carrot
Rippling/flux-sdk pull request #13
Opened 2023-11-09 17:50 UTC by zhedahht

Create a flux kit for Fertility(Carrot), with one capacity to update eligibility data that prepares for the CSV file to be sent to Carrot

2023-11-09 18:26 UTC, stevevls requested changes

2023-11-09 18:26 UTC, stevevls commented on flux_sdk/fertility_carrot/capabilities/update_eligibility_data/interface.py
> +class UpdateEligibilityData(ABC):
```suggestion
class ReportEligibilityData(ABC):
```
IIUC, we're reporting eligibility data to the 3rd party.  We want to reserve the update verb for when we're making changes in Rippling in response to data/actions from the 3rd party.

2023-11-09 18:26 UTC, stevevls commented on flux_sdk/fertility_carrot/capabilities/update_eligibility_data/interface.py
> +    def get_formatted_eligibility_data_file(
```suggestion
    def format_eligibility_data_file(
```

2023-11-09 18:26 UTC, stevevls commented on flux_sdk/fertility_carrot/capabilities/update_eligibility_data/interface.py
> +        Given a list of EmployeeEligibilityRecord, prepare a file for upload to the provider Carrot.
We shouldn't be calling out 3rd parties directly here, right?  Isn't the intention to use this kit for multiple providers?

2023-11-09 19:02 UTC, zhedahht commented on flux_sdk/fertility_carrot/capabilities/update_eligibility_data/interface.py
> +class UpdateEligibilityData(ABC):
Updated. Thanks.

2023-11-09 19:03 UTC, zhedahht commented on flux_sdk/fertility_carrot/capabilities/update_eligibility_data/interface.py
> +    def get_formatted_eligibility_data_file(
Updated. Thanks.

2023-11-09 19:03 UTC, zhedahht commented on flux_sdk/fertility_carrot/capabilities/update_eligibility_data/interface.py
> +        Given a list of EmployeeEligibilityRecord, prepare a file for upload to the provider Carrot.
Updated. Thanks.

2023-11-09 19:17 UTC, stevevls commented on flux_sdk/fertility/capabilities/report_eligibility_data/data_model.py
> +class EmployeeEligibilityRecord:
What are we expecting to be in this class?

2023-11-09 19:17 UTC, stevevls commented on flux_sdk/fertility/capabilities/report_eligibility_data/interface.py
> +    def format_eligibility_data_file(
Looking at this again, I think we can even shorten the name further.   WDYT?
```suggestion
    def format_eligibility_file(
```

2023-11-09 19:26 UTC, Kingpin007 commented on flux_sdk/fertility/capabilities/report_eligibility_data/data_model.py
> +class EmployeeEligibilityRecord:
Can we attempt to finalize what exact data will be required here?

2023-11-09 19:26 UTC, Kingpin007 commented on flux_sdk/fertility/capabilities/report_eligibility_data/interface.py
> +    implementation details, check their documentation.
Which whose documentation?

2023-11-09 19:27 UTC, Kingpin007 commented on flux_sdk/fertility/capabilities/report_eligibility_data/interface.py
> +        The file will be sent SFTP, so any compression or other formatting required by the provider
Nit, file will be sent via SFTP

2023-11-09 19:43 UTC, bryanbierce approved these changes

2023-11-09 19:46 UTC, bryanbierce commented on flux_sdk/fertility/capabilities/report_eligibility_data/interface.py
> +        """
I think you will also want a method for `get_file_name` to let the app implementer determine the name of the file for the company. Its unlikely that a future provider will use the same file naming pattern that carrot

2023-11-09 20:01 UTC, stevevls commented on flux_sdk/fertility/capabilities/report_eligibility_data/interface.py
> +        """
I'm trying to move us away from that type of function in general because I think that it can largely be solved via configuration.  We have an ongoing thread in #flux-eng about it.  I would suggest we adopt whatever pattern comes out of that convo.

2023-11-09 20:11 UTC, zhedahht commented on flux_sdk/fertility/capabilities/report_eligibility_data/data_model.py
> +class EmployeeEligibilityRecord:
Updated. Thanks.

2023-11-09 20:13 UTC, zhedahht commented on flux_sdk/fertility/capabilities/report_eligibility_data/interface.py
> +        """
Let's keep it as it's at this time.

2023-11-09 20:15 UTC, zhedahht commented on flux_sdk/fertility/capabilities/report_eligibility_data/interface.py
> +    def format_eligibility_data_file(
Updated. Thanks.

2023-11-09 20:15 UTC, zhedahht commented on flux_sdk/fertility/capabilities/report_eligibility_data/interface.py
> +    implementation details, check their documentation.
Updated. Thanks.

2023-11-09 20:18 UTC, stevevls commented on flux_sdk/fertility/capabilities/report_eligibility_data/data_model.py
> +class Gender(Enum):
Please use [the shared type](https://github.com/rippling/flux-sdk/blob/1b532b695c146ac31933b9ea487f8980a90b1fe3/flux_sdk/flux_core/data_models.py#L45-L45) instead of redclaring

2023-11-09 20:18 UTC, stevevls commented on flux_sdk/fertility/capabilities/report_eligibility_data/data_model.py
> +    role_id: str
"role" is confusing to folks outside rippling...let's rename to either `employee_id` or use the common [Employee](https://github.com/rippling/flux-sdk/blob/1b532b695c146ac31933b9ea487f8980a90b1fe3/flux_sdk/flux_core/data_models.py#L67-L68) type.

Since a lot of these fields are shared with `Employee`, I think it would create clarify to use the employee type because then the only other fields on this record would be specific to the fertility kit.

2023-11-09 21:45 UTC, zhedahht commented on flux_sdk/fertility/capabilities/report_eligibility_data/data_model.py
> +class Gender(Enum):
Updated. Thanks.

2023-11-09 22:01 UTC, stevevls commented on flux_sdk/fertility/capabilities/report_eligibility_data/data_model.py
> +    company_id: str
Is this redundant with the `company_info` that gets passed to `format_eligibility_file`?  Also, do start/end date refer to the employee or are they when the benefit is eligible/ineligible?  Is either one of them an optional field?

2023-11-09 23:22 UTC, zhedahht commented on flux_sdk/fertility/capabilities/report_eligibility_data/data_model.py
> +    company_id: str
Updated. Thanks.

2023-11-09 23:46 UTC, zhedahht commented on flux_sdk/fertility/capabilities/report_eligibility_data/data_model.py
> +    company_id: str
The eligibility end date is required:

![image](https://github.com/Rippling/flux-sdk/assets/6251205/8050e386-3c7e-4483-af28-fb312ba92ab9)

2023-11-10 17:46 UTC, stevevls approved these changes
Looks good.  Thanks for working through this with us!

2023-11-10 18:25 UTC, merged